druid:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    url0: jdbc:mysql://local_docker:3301/db0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url1: jdbc:mysql://local_docker:3301/db1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url2: jdbc:mysql://local_docker:3302/db0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url3: jdbc:mysql://local_docker:3302/db1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true